apiVersion: v1
kind: LimitRange
metadata:
  name: projet-limits
  namespace: projet-pst
spec:
  limits:
    - type: Container
      min:
        cpu: "50m"
        memory: "64Mi"
      max:
        cpu: "1500m"
        memory: "1Gi"
      defaultRequest:
        cpu: "100m"
        memory: "96Mi"
      default:
        cpu: "200m"
        memory: "160Mi"
