apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocessing
  namespace: projet-pst
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: preprocessing
  template:
    metadata:
      labels:
        app: preprocessing
    spec:
      containers:
        - name: preprocessing
          image: tp-text-preprocessing:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: INFERENCE_URL
              value: http://model-svc:8000
            - name: MONITORING_URL
              value: http://monitoring-svc:8002
          ports:
            - containerPort: 8001
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "192Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: inference-svc
  namespace: projet-pst
spec:
  type: NodePort
  selector:
    app: preprocessing
  ports:
    - port: 8000
      targetPort: 8001
