apiVersion: v1
kind: ResourceQuota
metadata:
  name: projet-quota
  namespace: projet-pst
spec:
  hard:
    requests.cpu: "3000m"
    requests.memory: "2Gi"
    limits.cpu: "3000m"
    limits.memory: "2Gi"
